### ISSUE TITLE
Limited Windows Support

### ISSUE THREAD

**Issue by mnordie** [lean-data-science/jupyterlab-credentialstore#2]
When installed from git on windows the PATH variable in kernel_connector.py become unparseable.
Also the location is maybe not ideal. I get a `C:\usr\local\bin\jupyter-credentialstore\kernel_connector.py` which is not what I want.

```
import kernel_connector as kc

Traceback (most recent call last):

  File "C:\Users\User\Miniconda3\envs\jupyterlab-ext\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-8-66b42edb3eeb>", line 1, in <module>
    import kernel_connector as kc

  File "C:\usr\local\bin\jupyter-credentialstore\kernel_connector.py", line 6
    PATH = 'C:\Users\User\Miniconda3\envs\jupyterlab-ext\Library\usr\bin/.credentialstore'
          ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by frankzickert** [comment]
I am afraid, Windows is not supported. The credentialstore works together with the jupyterlab-configuration (another repository). This configuration starts a Linux-Docker container and runs Jupyterlab. But the jupyterlab-configuration also runs on Linux/Mac only

**Comment by mnordie** [comment]
Ok, have you used it in a jupyterhub environment? That's my target platform but I havn't tried it yet. My concern is the location of the .credentialstore. If it's not located under user home it will not survive server shutdown.

**Comment by frankzickert** [comment]
I have not yet used it with JupyterHub - but with JupyterLab in a Docker-environment. A filesystem-volume prevents the file from not being deleted. Maybe you have startup-script that you can use to put the file at its place.
